package com.hkapps.hygienekleen.features.features_vendor.service.overtime.model.detailOvertimeChangeOpr

data class Data(
    val atDate: String,
    val createdAt: String,
    val createdByEmployeeId: Int,
    val description: String,
    val employeeCode: String,
    val employeeCodeCreated: String,
    val employeeId: Int,
    val employeeJobCode: String,
    val employeeName: String,
    val employeeNameCreated: String,
    val employeePhotoProfile: String,
    val employeePhotoProfileCreated: String,
    val employeeReplaceCode: String,
    val employeeReplaceId: Int,
    val employeeReplaceJobCode: String,
    val employeeReplaceName: String,
    val employeeReplacePhotoProfile: String,
    val endAt: String,
    val idDetailEmployeeProject: Int,
    val image: Any,
    val isPermission: String,
    val locationName: String,
    val overtimeId: Int,
    val permissionId: Any,
    val plottingId: Int,
    val projectId: String,
    val shiftDescription: String,
    val startAt: String,
    val status: String,
    val subLocationName: String,
    val title: String
)