package com.hkapps.hygienekleen.features.features_vendor.homescreen.monthlyworkreport.model.dailytarget

data class DailyTarget(
    val date : String,
    val name : String,
    val shift : String?,
    val totalTarget : Int,
    val targetsDone : Int,
    val totalDiverted : Int,
    val targetsNotFulfilled : Int,
    val percentTargetsDone : Double,
    val percentTargetsNotFulfilled : Double,
    val idDetailEmployeeProject : Int,
    val scheduleType : String,
    val userRole : String?,
    val closingStatus : String,
    val file : String?,
    val closedBy : String?,
    val closedAt : String?,
    val fileGenerated : Boolean,
    val emailSent : Boolean,
    val targetsRealization : Int,
    val percentTargetsRealization : Double,
    val percentTargetsNotApproved : Double,
    val targetsNotApproved : Int,
    val teamLeadTotalClosing: Int,
    val teamLeadDoneClosing : Int,
    val supervisorTotalClosing: Int,
    val supervisorDoneClosing : Int,
    val scanOutHasPassed : Boolean,
    val chiefNotExisted : Boolean,
    val idClosing : Int?,
)
