package com.hkapps.hygienekleen.features.features_client.complaint.model.detailHistoryComplaint

data class Data(
    val afterImage: String,
    val beforeImage: String,
    val clientId: Int,
    val clientName: String,
    val clientPhotoProfile: String,
    val comments: String,
    val complaintId: Int,
    val complaintType: String,
    val createdAt: String,
    val createdByEmployeeId: Int,
    val createdByEmployeeName: String,
    val createdByEmployeePhotoProfile: String,
    val date: String,
    val description: String,
    val doneAtDate: String,
    val doneAtTime: String,
    val image: String,
    val imageFourth: String,
    val imageThree: String,
    val imageTwo: String,
    val locationId: Int,
    val locationName: String,
    val notificationLevel: String,
    val processBy: Int,
    val processByEmployeeName: String,
    val processByEmployeePhotoProfile: String,
    val processImage: String,
    val projectId: String,
    val statusComplaint: String,
    val subLocationId: Int,
    val subLocationName: String,
    val time: String,
    val title: String,
    val worker: WorkerModel,
    val workerId: Int,
    val waitingAt: String,
    val processAt: String,
    val doneAt: String,
    val closedAt: String,
    val reportComments: String,
    val visitorOption: String,
    val visitorNumber: String,
    val visitorEmail: String,
    val escalation:String,
    val visitorObject: List<VisitorObjectClient>,
    val chemicalsName: ArrayList<ChemicalNameClient>,
    val typeJobs: String,
    val totalWorkers: Int


)