package com.hkapps.hygienekleen.features.features_vendor.service.complaint_internal.model.postdatacomplaintinternal

data class Data(
    val complaintId: Int,
    val clientId: Int,
    val createdByEmployeeId: Int,
    val complaintType: String,
    val projectId: String,
    val title: Int,
    val description: String,
    val comments: String,
    val reportComments: String,
    val image: String,
    val imageTwo: String,
    val imageThree: String,
    val imageFourth: String,
    val locationId: Int,
    val subLocationId: Int,
    val processBy: Int,
    val workerId: Int,
    val beforeImage: String,
    val processImage: String,
    val afterImage: String,
    val statusComplaint: String,
    val countStatusWaiting: Int,
    val countStatusOnProgress: Int,
    val doneAt: String,
    val createdAt: String,
)